# Generated by Django 4.1.5 on 2023-02-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_company_description_alter_company_location_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='Conversation',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chat',
            new_name='conversation',
        ),
    ]
