# Generated by Django 4.1.5 on 2023-02-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_chat_conversation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversation',
            new_name='Chat',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='conversation',
            new_name='chat',
        ),
    ]
