# Generated by Django 4.1.5 on 2023-06-17 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_conversation_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='chat_files/'),
            preserve_default=False,
        ),
    ]
